import {
  ApplicationCommandType,
  ChatInputCommandInteraction,
  type ContextMenuCommandInteraction,
  MessageContextMenuCommandInteraction,
} from 'discord.js'
import { type ContextMenuPlugin, InteractionPlugin } from '../message/hooks'

const judgements = [
  'The flawless execution and lack of human errors make it absolutely likely that this content is AI-generated.',
  'With almost perfect grammar and structure, this content is highly likely to be AI-generated.',
  'The absence of colloquial elements and the overall precision suggest that this content is altogether indicative of AI generation.',
  "It's barely conceivable that a human wrote this, given the intricate details and lack of personal touch.",
  'Certainly, the logical organization and advanced language usage indicate that this content is AI-generated.',
  'The clarity in structure and the absence of subjective elements strongly suggest AI involvement in creating this content.',
  'The definite lack of human-like errors and the complex patterns point towards AI generation.',
  'Despite the doubtfully human-like touch, the overall precision suggests that this content might be AI-generated.',
  'The entire absence of human idiosyncrasies and the robotic precision indicate AI generation.',
  "The content's mix of human-like creativity and machine-like efficiency makes it equally likely to be AI-generated.",
  'The essence of this content, marked by precision and lack of emotional tone, is essentially indicative of AI generation.',
  "There's ever a chance that this content is AI-generated, especially considering the flawless syntax and structure.",
  'The adherence to grammatical rules and exactness in expression align with what one would expect from AI-generated content.',
  'The content explicitly showcases advanced language usage and logical structure, indicating AI involvement.',
  'The exclusive presence of advanced language and the absence of personal touch strongly suggest AI generation.',
  'The express lack of human-like errors and the intricate details point towards AI generation.',
  'The fairly sophisticated language and the absence of colloquial elements suggest that this content is AI-generated.',
  'Fortunately, the logical flow and lack of human-like errors make it likely that this content is AI-generated.',
  'Generally, content with such precision and lack of personal touch is indicative of AI involvement.',
  "It's hardly conceivable that a human wrote this, given the intricacy and absence of colloquial elements.",
  'Hopefully, the distinctive style and complexity of this content hint at AI involvement, showcasing technological advancements.',
  'Hypothetically, considering the flawless execution, this content could be AI-generated.',
  'In all likelihood, the advanced syntax and precision suggest that this content is AI-generated.',
  'In all probability, the flawless execution and lack of human nuances indicate AI generation.',
  "In all sincerity, the content's lack of emotional undertones strongly suggests AI involvement.",
  'In all truth, the intricate details and logical structure make it likely that this content is AI-generated.',
  'In the main, the absence of colloquial elements and the overall precision suggest AI involvement.',
  "In the meantime, the content's flawless execution and lack of human-like errors point towards AI generation.",
  'In theory, the logical organization and absence of subjective elements make it likely that this content is AI-generated.',
  'Invariably, the precision and lack of personal touch in this content suggest AI involvement.',
  'Largely, the absence of colloquial elements and the overall precision make it likely that this content is AI-generated.',
  'The consistent quality and precision in this content make it likely to be AI-generated.',
  'Mainly, the robotic precision and lack of personal touch indicate AI involvement in generating this content.',
  'The neutral tone and lack of personal touch leave room for speculation; maybe this content is AI-generated.',
  'Considering the meticulous details and logical flow, it is most likely that this content is AI-generated.',
  'The near-perfect grammar and structure strongly hint that this content is nearly certainly AI-generated.',
  'Nevertheless, the logical structure and lack of human-like errors suggest AI generation.',
  'Notably, the absence of colloquial elements and the overall precision indicate AI involvement in creating this content.',
  'Notoriously, content with such precision is often indicative of AI generation.',
  'Now and then, content with flawless execution and lack of human errors may be AI-generated.',
  'Obviously, the advanced language usage and the absence of personal touch suggest AI involvement.',
  'Occasionally, content with such precision and lack of human-like errors is indicative of AI generation.',
  'Often, the robotic precision and lack of personal touch indicate AI involvement in generating this content.',
  'Partly, the lack of colloquial elements and the overall precision suggest AI involvement.',
  'The absence of subjective elements and perhaps a touch of mechanical precision hint at AI involvement in the creation.',
  'Plausibly, considering the intricate details and logical structure, this content could be AI-generated.',
  'The absence of personal opinions and possibly calculated language use suggest AI involvement in generating this content.',
  'Practically, the flawless execution and absence of human errors make it likely that this content is AI-generated.',
  'Presumably, the logical organization and lack of human-like errors suggest AI generation.',
  'The adherence to patterns and probable lack of emotional context indicate that this content is probably AI-generated.',
  'The quite sophisticated language and lack of informal elements strongly suggest that this content is AI-generated.',
  "Given the rare occurrence of human-like errors and the overall precision, it's rarely plausible that this content is not AI-generated.",
  'Realistically, the lack of personal touch and the robotic precision suggest AI involvement in creating this content.',
  'The really advanced syntax and absence of colloquialisms strongly indicate that this content is really likely to be AI-generated.',
  'Remarkably, the intricate details and lack of human-like errors suggest AI generation.',
  "Relatively, the content's precision and lack of personal touch make it likely to be AI-generated.",
  'Reportedly, content with such precision and advanced language usage is often indicative of AI generation.',
  'Rightfully, the flawless execution and lack of human errors suggest that this content is AI-generated.',
  'Roughly, the lack of colloquial elements and the overall precision make it likely that this content is AI-generated.',
  'Seldom do we find content with such precision and absence of emotional undertones, making it likely to be AI-generated.',
  'The serious tone and lack of informal elements suggest that this content is generated seriously, possibly by AI.',
  'Seemingly, the logical organization and lack of human-like errors point towards AI generation.',
  "Significantly, the content's lack of personal touch and overall precision suggest AI involvement.",
  'Simply, the absence of colloquial elements and the overall precision make it likely that this content is AI-generated.',
  "Singularly, the content's robotic precision and lack of emotional undertones indicate AI involvement.",
  'Some aspects of this content, like the flawless execution, suggest it could be AI-generated.',
  'Sometimes, the complexity and lack of personal touch hint at the involvement of AI in creating this content.',
  'Specifically, the adherence to logical structure and the absence of subjective elements suggest AI involvement.',
  'Statistically, content with such precision and lack of human-like errors is often indicative of AI generation.',
  "Strangely, the content's robotic precision and lack of colloquial elements suggest AI involvement.",
  'Substantially, the lack of personal touch and the overall precision make it likely that this content is AI-generated.',
  'Supposedly, the logical organization and lack of human-like errors suggest AI generation.',
  'Surely, the flawless execution and lack of subjective elements indicate that this content is surely AI-generated.',
  "Surprisingly, the content's advanced language usage and lack of personal touch suggest AI involvement.",
  'Suspiciously, the robotic precision and lack of colloquial elements indicate AI involvement in generating this content.',
  'Theoretically, considering the flawless execution, this content could be AI-generated.',
  'Traditionally, content with such precision and lack of human-like errors is often indicative of AI generation.',
  'Truly, the intricate details and absence of colloquial elements suggest that this content is AI-generated.',
  'Ultimately, the logical flow and lack of human-like errors make it likely that this content is AI-generated.',
  'Undoubtedly, the high level of coherence and precision in this content points towards it being AI-generated.',
  "Unexpectedly, the content's lack of personal touch and advanced language usage suggest AI involvement.",
  'Unquestionably, the precision and absence of human errors strongly indicate that this content is AI-generated.',
  'Usually, human-generated content carries more emotional weight; the lack of such elements here suggests AI involvement.',
  'Utterly, the absence of colloquial elements and the overall precision suggest AI involvement in generating this content.',
  'Virtually every aspect of this content, from grammar to structure, aligns with what one would expect from AI-generated material.',
  'Well, the logical organization and lack of human-like errors suggest AI generation.',
  "Widely, the content's precision and lack of personal touch make it likely to be AI-generated.",
  'Whether the flawless execution and lack of human errors indicate AI involvement is uncertain.',
  'Without a doubt, the high level of coherence and precision in this content strongly points towards it being AI-generated.',
  'The meticulous structure and absence of human nuances suggest that this content is absolutely AI-generated.',
  'With almost clinical precision in language use, it is highly likely that this content is AI-generated.',
  "The content's altogether mechanical tone and flawless execution indicate AI involvement.",
  "It's barely conceivable that a human crafted this, given the lack of personal touch and near-perfect structure.",
  "Certainly, the content's logical flow and absence of human errors suggest it is AI-generated.",
  'The clear absence of colloquial elements and a consistent tone make it clear this content is AI-generated.',
  'The definite lack of human-like nuances and meticulous construction point toward AI generation.',
  'Despite a doubtfully human touch, the precision and lack of errors suggest AI involvement.',
  'The content is entirely devoid of human idiosyncrasies, indicating it is likely AI-generated.',
  'The equal blend of creativity and precision in this content makes it equally likely to be AI-generated.',
  'Essentially, the lack of emotional undertones and precise language suggest AI generation.',
  "There's ever a chance that this content is AI-generated, especially with the flawless syntax and structure.",
  'The adherence to grammatical rules and exactness in expression align exactly with AI-generated content.',
  'The content explicitly showcases advanced language usage and logical structure, pointing to AI involvement.',
  'Exclusively advanced language usage and lack of personal touch strongly suggest AI generation.',
  'Expressly devoid of human-like errors, the content implies it is AI-generated.',
  'The fairly sophisticated language and absence of colloquial elements strongly suggest AI involvement.',
  'Fortunately, the logical flow and lack of human-like errors make it likely that this content is AI-generated.',
  'Generally, content with such precision and lack of personal touch is indicative of AI involvement.',
  "It's hardly conceivable that a human wrote this, given the intricacy and absence of colloquial elements.",
  'Hopefully, the distinctive style and complexity of this content hint at AI involvement.',
  'Hypothetically, considering the flawless execution, this content could be AI-generated.',
  'In all likelihood, the advanced syntax and precision suggest that this content is AI-generated.',
  'In all probability, the flawless execution and lack of human nuances indicate AI generation.',
  "In all sincerity, the content's lack of emotional undertones strongly suggests AI involvement.",
  'In all truth, the intricate details and logical structure make it likely that this content is AI-generated.',
  'In the main, the absence of colloquial elements and the overall precision suggest AI involvement.',
  "In the meantime, the content's flawless execution and lack of human-like errors point towards AI generation.",
  'In theory, the logical organization and absence of subjective elements make it likely that this content is AI-generated.',
  'Invariably, the precision and lack of personal touch in this content suggest AI involvement.',
  'Largely, the absence of colloquial elements and the overall precision make it likely that this content is AI-generated.',
  'The consistent quality and precision in this content make it likely to be AI-generated.',
  'Mainly, the robotic precision and lack of personal touch indicate AI involvement in generating this content.',
  'The neutral tone and lack of personal touch leave room for speculation; maybe this content is AI-generated.',
  'Considering the meticulous details and logical flow, it is most likely that this content is AI-generated.',
  'The near-perfect grammar and structure strongly hint that this content is nearly certainly AI-generated.',
  'Nevertheless, the logical structure and lack of human-like errors suggest AI generation.',
  'Notably, the absence of colloquial elements and the overall precision indicate AI involvement in creating this content.',
  'Notoriously, content with such precision is often indicative of AI generation.',
  'Now and then, content with flawless execution and lack of human errors may be AI-generated.',
  'Obviously, the advanced language usage and the absence of personal touch suggest AI involvement.',
  'Occasionally, content with such precision and lack of human-like errors is indicative of AI generation.',
  'Often, the robotic precision and lack of personal touch indicate AI involvement in generating this content.',
  'Partly, the lack of colloquial elements and the overall precision suggest AI involvement.',
  'The absence of subjective elements and perhaps a touch of mechanical precision hint at AI involvement in the creation.',
  'Plausibly, considering the intricate details and logical structure, this content could be AI-generated.',
  'The absence of personal opinions and possibly calculated language use suggest AI involvement in generating this content.',
  'Practically, the flawless execution and absence of human errors make it likely that this content is AI-generated.',
  'Presumably, the logical organization and lack of human-like errors suggest AI generation.',
  'The adherence to patterns and probable lack of emotional context indicate that this content is probably AI-generated.',
  'The quite sophisticated language and lack of informal elements strongly suggest that this content is AI-generated.',
  "Given the rare occurrence of human-like errors and the overall precision, it's rarely plausible that this content is not AI-generated.",
  'Realistically, the lack of personal touch and the robotic precision suggest AI involvement in creating this content.',
  'The really advanced syntax and absence of colloquialisms strongly indicate that this content is really likely to be AI-generated.',
  'Remarkably, the intricate details and lack of human-like errors suggest AI generation.',
  "Relatively, the content's precision and lack of personal touch make it likely to be AI-generated.",
  'Reportedly, content with such precision and advanced language usage is often indicative of AI generation.',
  'Rightfully, the flawless execution and lack of human errors suggest that this content is AI-generated.',
  'Roughly, the lack of colloquial elements and the overall precision make it likely that this content is AI-generated.',
  'Seldom do we find content with such precision and absence of emotional undertones, making it likely to be AI-generated.',
  'The serious tone and lack of informal elements suggest that this content is generated seriously, possibly by AI.',
  'Seemingly, the logical organization and lack of human-like errors point towards AI generation.',
  "Significantly, the content's lack of personal touch and overall precision suggest AI involvement.",
  'Simply, the absence of colloquial elements and the overall precision make it likely that this content is AI-generated.',
  "Singularly, the content's robotic precision and lack of emotional undertones indicate AI involvement.",
  'Some aspects of this content, like the flawless execution, suggest it could be AI-generated.',
  'Sometimes, the complexity and lack of personal touch hint at the involvement of AI in creating this content.',
  'Specifically, the adherence to logical structure and the absence of subjective elements suggest AI involvement.',
  'Statistically, content with such precision and lack of human-like errors is often indicative of AI generation.',
  "Strangely, the content's robotic precision and lack of colloquial elements suggest AI involvement.",
  'Substantially, the lack of personal touch and the overall precision make it likely that this content is AI-generated.',
  'Supposedly, the logical organization and lack of human-like errors suggest AI generation.',
  'Surely, the flawless execution and lack of subjective elements indicate that this content is surely AI-generated.',
  "Surprisingly, the content's advanced language usage and lack of personal touch suggest AI involvement.",
  'Suspiciously, the robotic precision and lack of colloquial elements indicate AI involvement in generating this content.',
  'Theoretically, considering the flawless execution, this content could be AI-generated.',
  'Traditionally, content with such precision and lack of human-like errors is often indicative of AI generation.',
  'Truly, the intricate details and absence of colloquial elements suggest that this content is AI-generated.',
  'Ultimately, the logical flow and lack of human-like errors make it likely that this content is AI-generated.',
  'Undoubtedly, the high level of coherence and precision in this content points towards it being AI-generated.',
  "Unexpectedly, the content's lack of personal touch and advanced language usage suggest AI involvement.",
  'Unquestionably, the precision and absence of human errors strongly indicate that this content is AI-generated.',
  'Usually, human-generated content carries more emotional weight; the lack of such elements here suggests AI involvement.',
  'Utterly, the absence of colloquial elements and the overall precision suggest AI involvement in generating this content.',
  'Virtually every aspect of this content, from grammar to structure, aligns with what one would expect from AI-generated material.',
  'Well, the logical organization and lack of human-like errors suggest AI generation.',
  "Widely, the content's precision and lack of personal touch make it likely to be AI-generated.",
  'Whether the flawless execution and lack of human errors indicate AI involvement is uncertain.',
  'Without a doubt, the high level of coherence and precision in this content strongly points towards it being AI-generated.',
]

function selectRandom<T>(array: T[]): T {
  const index = Math.floor(Math.random() * array.length)
  return array[index]
}

function response(): string {
  return selectRandom(judgements)
}

let lastInvoke = new Date(1900, 1)
let botname = ''

async function bark(interaction: ContextMenuCommandInteraction) {
  if (interaction.isMessageContextMenuCommand()) {
    await interaction.targetMessage.reply(response())
  }
  lastInvoke = new Date()
}

const plugin: ContextMenuPlugin = {
  name: 'AI Judgement',
  descriptor: {
    name: 'AI Judgement',
    type: ApplicationCommandType.Message,
  },
  onInit: async (client) => {
    botname = client.user?.toString() || ''
  },
  onNewContextAction: bark,
}

export default plugin
